In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv(r"D:\\New folder\\train_gbW7HTd.csv")
df
df["Workclass"].fillna("No Workclass", inplace = True) 
df["Occupation"].fillna("No Occupation", inplace = True) 
df["Native_Country"].fillna("No Native_Country", inplace = True)   
df.head()

,ID,Age,Workclass,Education,Marital_Status,Occupation,Relationship,Race,Sex,Hours_Per_Week,Native_Country,Income_Group
0,1,39,State-gov,Bachelors,Never-married,Adm-clerical,Not-in-family,White,Male,40,United-States,<=50K
1,2,50,Self-emp-not-inc,Bachelors,Married-civ-spouse,Exec-managerial,Husband,White,Male,13,United-States,<=50K
2,3,38,Private,HS-grad,Divorced,Handlers-cleaners,Not-in-family,White,Male,40,United-States,<=50K
3,4,53,Private,11th,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,40,United-States,<=50K
4,5,28,Private,Bachelors,Married-civ-spouse,Prof-specialty,Wife,Black,Female,40,Cuba,<=50K

In [3]:
df1 = pd.read_csv(r"D:\\New folder\\test_2AFBew7.csv")
df1["Workclass"].fillna("No Workclass", inplace = True) 
df1["Occupation"].fillna("No Occupation", inplace = True) 
df1["Native_Country"].fillna("No Native_Country", inplace = True)   
#df1.head()

In [4]:
inputs = df.drop('Income_Group',axis='columns')
target = df["Income_Group"]

In [5]:
from sklearn.preprocessing import LabelEncoder
ID_A = LabelEncoder()
Age_A= LabelEncoder()
Workclass_A = LabelEncoder()
Education_A=LabelEncoder()
Marital_Status_A=LabelEncoder()
Occupation_A=LabelEncoder()
Relationship_A=LabelEncoder()
Race_A =LabelEncoder()
Sex_A=LabelEncoder()
Hours_Per_Week_A=LabelEncoder()
Native_Country_A=LabelEncoder()

In [6]:
inputs['ID_n'] = ID_A.fit_transform(inputs['ID'])
inputs['Age_n'] = Age_A.fit_transform(inputs['Age'])
inputs['Workclass_n'] = Workclass_A.fit_transform(inputs['Workclass'])
inputs['Education_n'] = Education_A.fit_transform(inputs['Education'])
inputs['Marital_Status_n'] = Marital_Status_A.fit_transform(inputs['Marital_Status'])
inputs['Occupation_n'] = Occupation_A.fit_transform(inputs['Occupation'])
inputs['Relationship_n'] = Relationship_A.fit_transform(inputs['Relationship'])
inputs['Race_n'] = Race_A.fit_transform(inputs['Race'])
inputs['Sex_n'] = Sex_A.fit_transform(inputs['Sex'])
inputs['Hours_Per_Week_n'] = Hours_Per_Week_A.fit_transform(inputs['Hours_Per_Week'])
inputs['Native_Country_n'] = Native_Country_A.fit_transform(inputs['Native_Country'])

In [7]:
inputs_n = inputs.drop(['ID','Age','Workclass','Education','Marital_Status','Occupation','Relationship','Race','Sex','Hours_Per_Week','Native_Country',],axis='columns')

In [8]:
from sklearn.preprocessing import LabelEncoder
ID_B = LabelEncoder()
Age_B= LabelEncoder()
Workclass_B = LabelEncoder()
Education_B=LabelEncoder()
Marital_Status_B=LabelEncoder()
Occupation_B=LabelEncoder()
Relationship_B=LabelEncoder()
Race_B =LabelEncoder()
Sex_B=LabelEncoder()
Hours_Per_Week_B=LabelEncoder()
Native_Country_B=LabelEncoder()

In [9]:
df1['ID_n1'] = ID_B.fit_transform(df1['ID'])
df1['Age_n1'] = Age_B.fit_transform(df1['Age'])
df1['Workclass_n1'] = Workclass_B.fit_transform(df1['Workclass'])
df1['Education_n1'] = Education_B.fit_transform(df1['Education'])
df1['Marital_Status_n1'] = Marital_Status_B.fit_transform(df1['Marital_Status'])
df1['Occupation_n1'] = Occupation_B.fit_transform(df1['Occupation'])
df1['Relationship_n1'] = Relationship_B.fit_transform(df1['Relationship'])
df1['Race_n1'] = Race_B.fit_transform(df1['Race'])
df1['Sex_n1'] = Sex_B.fit_transform(df1['Sex'])
df1['Hours_Per_Week_n1'] = Hours_Per_Week_B.fit_transform(df1['Hours_Per_Week'])
df1['Native_Country_n1'] = Native_Country_B.fit_transform(df1['Native_Country'])

In [10]:
inputs_n1 = df1.drop(['ID','Age','Workclass','Education','Marital_Status','Occupation','Relationship','Race','Sex','Hours_Per_Week','Native_Country',],axis='columns')

In [11]:
from sklearn import tree
model = tree.DecisionTreeClassifier()
model.fit(inputs_n, target)
model.score(inputs_n,target)
model.predict([[0,22,7,9,4,0,1,4,1,39,39]])

array(['<=50K'], dtype=object)

In [12]:
y_pred=model.predict(inputs_n1)
#Imcome_predicted = pd.DataFrame(y_pred)
#Imcome_predicted

In [13]:
df1 = pd.read_csv(r"D:\\New folder\\test_2AFBew7.csv")
y_pred=model.predict(inputs_n1)
df1["Imcome_predicted"] = y_pred
df1

,ID,Age,Workclass,Education,Marital_Status,Occupation,Relationship,Race,Sex,Hours_Per_Week,Native_Country,Imcome_predicted
0,32562,25,Private,11th,Never-married,Machine-op-inspct,Own-child,Black,Male,40,United-States,<=50K
1,32563,38,Private,HS-grad,Married-civ-spouse,Farming-fishing,Husband,White,Male,50,United-States,<=50K
2,32564,28,Local-gov,Assoc-acdm,Married-civ-spouse,Protective-serv,Husband,White,Male,40,United-States,<=50K
3,32565,44,Private,Some-college,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,40,United-States,>50K
4,32566,18,NaN,Some-college,Never-married,NaN,Own-child,White,Female,30,United-States,<=50K
5,32567,34,Private,10th,Never-married,Other-service,Not-in-family,White,Male,30,United-States,<=50K
6,32568,29,NaN,HS-grad,Never-married,NaN,Unmarried,Black,Male,40,United-States,<=50K
7,32569,63,Self-emp-not-inc,Prof-school,Married-civ-spouse,Prof-specialty,Husband,White,Male,32,United-States,>50K
8,32570,24,Private,Some-college,Never-married,Other-service,Unmarried,White,Female,40,United-States,<=50K
9,32571,55,Private,7th-8th,Married-civ-spouse,Craft-repair,Husband,White,Male,10,United-States,<=50K
10,32572,65,Private,HS-grad,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,40,United-States,<=50K
11,32573,36,Federal-gov,Bachelors,Married-civ-spouse,Adm-clerical,Husband,White,Male,40,United-States,<=50K
12,32574,26,Private,HS-grad,Never-married,Adm-clerical,Not-in-family,White,Female,39,United-States,<=50K
13,32575,58,NaN,HS-grad,Married-civ-spouse,NaN,Husband,White,Male,35,United-States,>50K
14,32576,48,Private,HS-grad,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,48,United-States,<=50K
15,32577,43,Private,Masters,Married-civ-spouse,Exec-managerial,Husband,White,Male,50,United-States,>50K
16,32578,20,State-gov,Some-college,Never-married,Other-service,Own-child,White,Male,25,United-States,<=50K
17,32579,43,Private,HS-grad,Married-civ-spouse,Adm-clerical,Wife,White,Female,30,United-States,<=50K
18,32580,37,Private,HS-grad,Widowed,Machine-op-inspct,Unmarried,White,Female,20,United-States,<=50K
19,32581,40,Private,Doctorate,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,45,NaN,>50K
20,32582,34,Private,Bachelors,Married-civ-spouse,Tech-support,Husband,White,Male,47,United-States,>50K
21,32583,34,Private,Some-college,Never-married,Other-service,Own-child,Black,Female,35,United-States,<=50K
22,32584,72,NaN,7th-8th,Divorced,NaN,Not-in-family,White,Female,6,United-States,<=50K
23,32585,25,Private,Bachelors,Never-married,Prof-specialty,Not-in-family,White,Male,43,Peru,<=50K
24,32586,25,Private,Bachelors,Married-civ-spouse,Prof-specialty,Husband,White,Male,40,United-States,<=50K
25,32587,45,Self-emp-not-inc,HS-grad,Married-civ-spouse,Craft-repair,Husband,White,Male,90,United-States,<=50K
26,32588,22,Private,HS-grad,Never-married,Adm-clerical,Own-child,White,Male,20,United-States,<=50K
27,32589,23,Private,HS-grad,Separated,Machine-op-inspct,Unmarried,Black,Male,54,United-States,<=50K
28,32590,54,Private,HS-grad,Married-civ-spouse,Craft-repair,Husband,White,Male,35,United-States,>50K
29,32591,32,Self-emp-not-inc,Some-college,Never-married,Prof-specialty,Not-in-family,White,Male,60,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...
16251,48813,81,NaN,Assoc-voc,Married-civ-spouse,NaN,Husband,White,Male,20,United-States,<=50K
16252,48814,60,Private,Assoc-voc,Married-civ-spouse,Prof-specialty,Husband,White,Male,40,United-States,<=50K
16253,48815,39,Private,Bachelors,Never-married,Tech-support,Not-in-family,White,Female,40,United-States,<=50K
16254,48816,38,Private,Masters,Married-civ-spouse,Prof-specialty,Husband,White,Male,50,United-States,>50K
16255,48817,43,Local-gov,Masters,Married-civ-spouse,Exec-managerial,Husband,White,Male,50,United-States,>50K
16256,48818,23,Private,HS-grad,Never-married,Machine-op-inspct,Own-child,White,Male,40,United-States,<=50K
16257,48819,73,Self-emp-inc,Some-college,Divorced,Exec-managerial,Not-in-family,White,Female,40,United-States,<=50K
16258,48820,35,Private,Some-college,Married-civ-spouse,Protective-serv,Husband,White,Male,40,United-States,>50K
16259,48821,66,Private,HS-grad,Widowed,Sales,Other-relative,White,Female,8,United-States,<=50K
16260,48822,27,Private,Some-college,Never-married,Sales,Not-in-family,White,Female,45,United-States,<=50K
16261,48823,40,Private,Prof-school,Married-civ-spouse,Prof-specialty,Husband,White,Male,55,United-States,>50K
16262,48824,51,Private,HS-grad,Married-civ-spouse,Craft-repair,Husband,White,Male,40,United-States,>50K
16263,48825,22,Private,Some-college,Never-married,Craft-repair,Own-child,White,Male,40,United-States,<=50K
16264,48826,64,Self-emp-not-inc,HS-grad,Widowed,Farming-fishing,Not-in-family,White,Male,32,United-States,<=50K
16265,48827,50,Local-gov,Masters,Married-civ-spouse,Prof-specialty,Wife,White,Female,40,NaN,<=50K
16266,48828,55,Private,HS-grad,Separated,Priv-house-serv,Not-in-family,White,Female,32,United-States,<=50K
16267,48829,38,Private,Assoc-voc,Never-married,Adm-clerical,Unmarried,Black,Female,40,United-States,<=50K
16268,48830,58,Private,Assoc-acdm,Divorced,Prof-specialty,Not-in-family,White,Male,36,United-States,<=50K
16269,48831,32,Private,HS-grad,Married-civ-spouse,Handlers-cleaners,Husband,White,Male,40,United-States,<=50K
16270,48832,48,Private,HS-grad,Married-civ-spouse,Adm-clerical,Husband,White,Male,40,United-States,>50K
16271,48833,61,Private,HS-grad,Married-civ-spouse,Sales,Husband,White,Male,48,United-States,<=50K
16272,48834,31,Private,HS-grad,Married-civ-spouse,Craft-repair,Husband,White,Male,40,United-States,<=50K
16273,48835,25,Private,HS-grad,Never-married,Other-service,Own-child,White,Female,40,United-States,<=50K
16274,48836,48,Local-gov,Masters,Divorced,Other-service,Not-in-family,White,Male,40,United-States,<=50K
16275,48837,33,Private,Bachelors,Never-married,Prof-specialty,Own-child,White,Male,40,United-States,<=50K
16276,48838,39,Private,Bachelors,Divorced,Prof-specialty,Not-in-family,White,Female,36,United-States,<=50K
16277,48839,64,NaN,HS-grad,Widowed,NaN,Other-relative,Black,Male,40,United-States,<=50K
16278,48840,38,Private,Bachelors,Married-civ-spouse,Prof-specialty,Husband,White,Male,50,United-States,>50K
16279,48841,44,Private,Bachelors,Divorced,Adm-clerical,Own-child,Asian-Pac-Islander,Male,40,United-States,<=50K
16280,48842,35,Self-emp-inc,Bachelors,Married-civ-spouse,Exec-managerial,Husband,White,Male,60,United-States,>50K

In [14]:
df1.to_csv("D:\\New folder\\Prediced.csv")